<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

In [2]:
import numpy as np

## Exercise 1: Total recall

|**Term**|**Definition**|
|--------|--------------|
|Subsetting|to 'select' a smaller set from a set of data|
|Indexing|selecting one element|
|Slicing|to select a range of elements|
|Masking|a way to subset by using a condition|

## Exercise 2: Show me the 'odd' letters

In [47]:
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])


np_array_2d[:,0]

array(['1', '3', '2', '4', '5', '7', '6', '8', '10', '9'], dtype='<U21')

In [ ]:
#array_name.astype() in numpy converts from one type of data to another (e.g. str to int)--->"array_name.astype()=CHANGE THE TYPE"
first_column_int = np_array_2d[:,0].astype(int)            #converted the first entry column into an array of integers so we can do operations and mask.

In [53]:
remainder = first_column_int % 2
remainder

array([1, 1, 0, 0, 1, 1, 0, 0, 0, 1])

In [55]:
mask = first_column_int % 2 == 1
mask

array([ True,  True, False, False,  True,  True, False, False, False,
        True])

In [ ]:
np_array_2d[mask]       #only outputs rows where remainder of first_column_int/2 is 1 (odd rows)

array([['1', 'A'],
       ['3', 'C'],
       ['5', 'E'],
       ['7', 'G'],
       ['9', 'I']], dtype='<U21')

## Exercise 3

In [66]:
array=np.array([[66, 50, 57, -1, -1],
                [92, -1, 88, -1, -1],
                [75, -1, -1, 76, -1],
                [-1, 51, 87, -1, -1],
                [71, -1, 67, -1, 69]])

mask_1 = array < 50

mask_2 = array == 50

mask_3 = array > 50

array[mask_1]=-1
array[mask_2]=0
array[mask_3]=1

array

array([[ 1,  0,  1, -1, -1],
       [ 1, -1,  1, -1, -1],
       [ 1, -1, -1,  1, -1],
       [-1,  1,  1, -1, -1],
       [ 1, -1,  1, -1,  1]])