<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

# What to expect in this chapter

In [4]:
import numpy as np

# 1 Subsetting: Indexing and Slicing

Subsetting means to ‘select’.
Indexing refers to selecting one element.
Slicing refers to selecting a range of elements.


## 1.1 Lists & Arrays in 1D | Subsetting & Indexing

In [5]:
py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]
np_array = np.array(py_list)

# Pick one
x = py_list  # OR
x = np_array

## 1.2 Arrays only | Subsetting by masking

In [6]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_mask = np_array > 3
my_mask

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [9]:
np_array[my_mask] #makes the mask elements that are true to be a np array, gives you a subset


array([ 4,  5,  6,  7,  8,  9, 10])

In [10]:
np_array[~my_mask] #basically gives you the complement of the subset above

array([1, 2, 3])

## 1.3 Lists & Arrays in 2D | Indexing & Slicing

## 1.4 Growing lists

# Some loose ends

## 1.5 Tuples

In [7]:
mytuple = (1,2,3,4,5,5)

mytuple.count(5) #counts how many of each element there are

2

CANNOT be appended or changed at all

## 1.6 Be VERY careful when copying

In [ ]:
x=[1, 2, 3]
y=x           # DON'T do this!
z=x           # DON'T do this!

In [ ]:
x=[1, 2, 3]
y=x.copy()    #RIGHT WAY TO COPY A LIST!!!
z=x.copy()

## Footnotes