<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

# What to expect in this chapter

In [13]:
import numpy as np

# 1 Lists, Arrays & Dictionaries

**Python Lists**

Usually MUCH easier and faster to append

In [14]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

**Numpy Array**

harder to append but very powerful

In [15]:
np_super_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"])
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])

**DICTIONARIES**

as the name suggests

In [16]:
superhero_info = {
    "Natasha Romanoff": "Black Widow",
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}

In [17]:
# CAN CONVERT:
np_super_names = np.array(py_super_names)

## 1.1 Let’s compare

To access lists: 

## 1.2 Accessing data from a list (or array)

In [18]:
py_super_names[0]

'Black Widow'

In [19]:
py_real_names[2]

'Stephen Strange'

you can use negative indexing to go backwards, like 
```python
    py_super_name[-1] 
```
will output Doctor Strange

## 1.3 Accessing data from a dictionary

Indexing is NOT supported the way it is for lists or tuples or arrays

In [20]:
superhero_info = {
    "Natasha Romanoff": "Black Widow",
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}

In [21]:
superhero_info.keys() #to turn the keys into a separate list

dict_keys(['Natasha Romanoff', 'Tony Stark', 'Stephen Strange'])

In [22]:
superhero_info.values() #to turn the values/definitions into a separate list 

dict_values(['Black Widow', 'Iron Man', 'Doctor Strange'])


**NUMPY DOES NOT CONTAIN DICTIONARIES**

## 1.4 Higher dimensional lists

In [23]:
py_superhero_info = [['Natasha Romanoff', 'Black Widow'],
                     ['Tony Stark', 'Iron Man'],
                     ['Stephen Strange', 'Doctor Strange']]

# 2 Lists vs. Arrays

## 2.1 Size

In [24]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)      # Reusing the Python list 
                                        # to create a NEW
                                        # NumPy array

In [25]:
len(py_list_2d)
len(np_array_2d)
np_array_2d.shape

(10, 2)

The above (np_array_2d.shape) tells me both the amount of entries in the 2d list (the grouped in [] entries) AND also tells me the dimension of the list (2D in this case so 2):

resulting output of 
```python
np_array_2d.shape
``` 
---> (10, 2)

## 2.2 Arrays are fussy about type

In [26]:
py_list = [1, 1.5, 'A']
np_array = np.array(py_list)

py_list
np_array

array(['1', '1.5', 'A'], dtype='<U32')

## 2.3 Adding a number

In [27]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         # Reusing the Python list
                                     # to create a NEW
                                     # NumPy array

np_array + 10 #Adds 10 to all elements

array([11, 12, 13, 14, 15])

In [28]:
py_list + 10        # Won't work! Only works with arrays and numpy arrays

TypeError: can only concatenate list (not "int") to list

## 2.4 Adding another list

In [ ]:
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)

In [ ]:
py_list_1 + py_list_2
np_array_1 + np_array_2.   #its like vector addition each like index is added to the other's

array([11, 22, 33, 44, 55])

## 2.5 Multiplying by a Number

In [ ]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)   #CONVERT TO np.array FIRST      

In [32]:
py_list*2
np_array*2

array([ 2,  4,  6,  8, 10])

## 2.6 Squaring

## 2.7 Asking questions ---> VERY USEFUL

In [ ]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [ ]:
#py_list > 2 # DOESNT WORK

np_array > 2

array([False, False,  True,  True,  True])

Above shows which indices in the list contain numbers that are >2 (as booleans)

Below the entries that are <= 2 are all eliminated from the np_array

In [34]:
mask=np_array>2
np_array[mask]

array([3, 4, 5])

## 2.8 Mathematics

In [ ]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [ ]:
sum(py_list)     # sum() is a base Python function
max(py_list)     # max() is a base Python function
min(py_list)     # min() is a base Python function
np_array.sum()
np_array.max()
np_array.min()
np_array.mean()
np_array.std()

np.float64(1.4142135623730951)

In [ ]:
#Output will be (ARRAYS):
np.int64(15)
np.int64(5)
np.int64(1)
np.float64(3.0)
np.float64(1.4142135623730951)

In [29]:
#Outputs will be (LISTS):
sum(py_list)     # sum() is a base Python function
max(py_list)     # max() is a base Python function
min(py_list) 

# outputs:
15
5
1
#py_list.sum()   # Won't work!

1

## Footnotes

AS a rule of thumb, convert lists to numpy arrays and THEN do operations

Can use dictionaries to store constantss or passwords or smth